import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { toast } from "@/hooks/use-toast";
import { 
  Plus, 
  Edit, 
  Trash2, 
  Save, 
  Printer, 
  Bell, 
  BellOff,
  AlertTriangle,
  TrendingUp,
  Package,
  Users,
  DollarSign,
  BarChart3,
  Table,
  Activity
} from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

// New data interfaces based on specifications
interface ProductQuantity {
  [product: string]: number;
}

interface ReminderAlert {
  Message: string;
  Date: string;
}

interface RecentActivityItem {
  Activity: string;
  Timestamp: string;
}

interface DashboardData {
  id: string;
  fy: string;
  TodayArrivals: ProductQuantity;
  TodaySales: ProductQuantity;
  PendingStock: ProductQuantity;
  PendingBalance: number;
  PendingKhata: number;
  ReminderAlerts: ReminderAlert[];
  QuickActions: string[];
  RecentActivity: RecentActivityItem[];
  createdAt: string;
  updatedAt: string;
}

interface DashboardModuleProps {
  currentFY: string;
  onFYChange: (fy: string) => void;
}

// Mock data for testing - based on specifications
const getMockDashboardData = (fy: string): DashboardData => {
  const baseData = {
    TodayArrivals: { "Onion": 250, "Potato": 500, "Garlic": 70 },
    TodaySales: { "Onion": 150, "Potato": 300, "Garlic": 40 },
    PendingBalance: 25000,
    PendingKhata: 18000,
    ReminderAlerts: [
      { Message: "Suraj Varma ₹2000 overdue", Date: "2025-09-21" },
      { Message: "Payment due from Lot ABC-123", Date: "2025-09-22" }
    ],
    QuickActions: ["Add New Lot", "Create Bill", "Send Invoice", "Update Stock", "Print Report", "View Ledger"],
    RecentActivity: [
      { Activity: "Sold 150 Onion", Timestamp: "2025-09-21 07:00" },
      { Activity: "Added new lot Potato-500", Timestamp: "2025-09-21 06:30" },
      { Activity: "Payment received ₹5000", Timestamp: "2025-09-21 06:00" },
      { Activity: "Updated Garlic stock", Timestamp: "2025-09-21 05:45" }
    ]
  };

  // Auto-calculate PendingStock = TodayArrivals - TodaySales
  const PendingStock: ProductQuantity = {};
  Object.keys(baseData.TodayArrivals).forEach(product => {
    const arrivals = baseData.TodayArrivals[product] || 0;
    const sales = baseData.TodaySales[product] || 0;
    PendingStock[product] = arrivals - sales;
  });

  return {
    id: `dashboard-${fy}`,
    fy,
    ...baseData,
    PendingStock,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
};

const generatePDF = (data: DashboardData) => {
  const formatProductQuantity = (products: ProductQuantity) => 
    Object.entries(products).map(([product, qty]) => `${product}: ${qty}`).join(', ');

  const content = `
MANDI360PRO - DASHBOARD SUMMARY
Financial Year: ${data.fy}
Generated: ${new Date().toLocaleString()}
================================

TODAY'S ARRIVALS
${formatProductQuantity(data.TodayArrivals)}

TODAY'S SALES
${formatProductQuantity(data.TodaySales)}

PENDING STOCK
${formatProductQuantity(data.PendingStock)}

PENDING BALANCE
Cash/Balance: ₹${data.PendingBalance.toLocaleString()}
Khata: ₹${data.PendingKhata.toLocaleString()}
Total: ₹${(data.PendingBalance + data.PendingKhata).toLocaleString()}

REMINDER ALERTS
${data.ReminderAlerts.map(alert => `• ${alert.Message} (${alert.Date})`).join('\n')}

QUICK ACTIONS
${data.QuickActions.map(action => `• ${action}`).join('\n')}

RECENT ACTIVITY
${data.RecentActivity.map(activity => `• ${activity.Activity} - ${activity.Timestamp}`).join('\n')}

Report generated by Mandi360pro
  `;
  
  // Create and download as text file (in real app, would use proper PDF library)
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `dashboard-summary-${data.fy}-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export default function DashboardModule({ currentFY, onFYChange }: DashboardModuleProps) {
  const [dashboardData, setDashboardData] = useState<DashboardData | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingField, setEditingField] = useState<string | null>(null);
  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
  
  const [formData, setFormData] = useState({
    field: "",
    value: "",
    fy: currentFY
  });

  // Load dashboard data from localStorage on mount
  useEffect(() => {
    const savedData = localStorage.getItem(`mandi360pro-dashboard-${currentFY}`);
    if (savedData) {
      try {
        const parsedData = JSON.parse(savedData);
        setDashboardData(parsedData);
      } catch (error) {
        console.error('Error loading dashboard data from localStorage:', error);
        setDashboardData(getMockDashboardData(currentFY));
      }
    } else {
      // Initialize with mock data
      const mockData = getMockDashboardData(currentFY);
      setDashboardData(mockData);
      localStorage.setItem(`mandi360pro-dashboard-${currentFY}`, JSON.stringify(mockData));
    }
  }, [currentFY]);

  // Save dashboard data to localStorage whenever data changes
  useEffect(() => {
    if (dashboardData) {
      localStorage.setItem(`mandi360pro-dashboard-${currentFY}`, JSON.stringify(dashboardData));
    }
  }, [dashboardData, currentFY]);

  // Multi-window localStorage sync
  useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === `mandi360pro-dashboard-${currentFY}` && e.newValue) {
        try {
          const newData = JSON.parse(e.newValue);
          setDashboardData(newData);
          toast({
            title: "Data Synced",
            description: "Dashboard updated from another window"
          });
        } catch (error) {
          console.error('Error syncing dashboard data:', error);
        }
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, [currentFY]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.ctrlKey) {
        switch (e.key.toLowerCase()) {
          case 'n':
            e.preventDefault();
            handleAdd();
            break;
          case 'e':
            e.preventDefault();
            if (dashboardData) {
              handleEdit("TodayArrivals"); // Edit arrivals by default
            }
            break;
          case 'd':
            e.preventDefault();
            if (dashboardData) {
              setIsDeleteModalOpen(true);
            }
            break;
          case 's':
            e.preventDefault();
            if (isModalOpen) {
              handleSave();
            }
            break;
          case 'p':
            e.preventDefault();
            handlePrint();
            break;
          case 'r':
            e.preventDefault();
            toggleReminders();
            break;
        }
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [isModalOpen, dashboardData]);

  const handleAdd = () => {
    setEditingField(null);
    setFormData({
      field: "TodayArrivals",
      value: "",
      fy: currentFY
    });
    setIsModalOpen(true);
  };

  const handleEdit = (field: string) => {
    setEditingField(field);
    let value = "";
    if (dashboardData) {
      switch (field) {
        case "TodayArrivals":
        case "TodaySales":
          value = JSON.stringify(dashboardData[field as keyof DashboardData]);
          break;
        case "PendingBalance":
        case "PendingKhata":
          value = dashboardData[field as keyof DashboardData].toString();
          break;
        case "ReminderAlerts":
        case "QuickActions":
        case "RecentActivity":
          value = JSON.stringify(dashboardData[field as keyof DashboardData]);
          break;
        default:
          value = "";
      }
    }
    setFormData({
      field,
      value,
      fy: currentFY
    });
    setIsModalOpen(true);
  };

  const handleSave = () => {
    // Validation
    if (!formData.field.trim()) {
      toast({
        title: "Error",
        description: "Field is required",
        variant: "destructive"
      });
      return;
    }

    if (!formData.value.trim()) {
      toast({
        title: "Error", 
        description: "Value is required",
        variant: "destructive"
      });
      return;
    }

    try {
      let parsedValue: any;
      const field = formData.field;

      // Parse value based on field type
      switch (field) {
        case "TodayArrivals":
        case "TodaySales":
          parsedValue = JSON.parse(formData.value);
          // Validate it's an object with string keys and number values
          if (typeof parsedValue !== 'object' || Array.isArray(parsedValue)) {
            throw new Error("Must be an object with product names and quantities");
          }
          break;
        case "PendingBalance":
        case "PendingKhata":
          parsedValue = parseFloat(formData.value);
          if (isNaN(parsedValue) || parsedValue < 0) {
            throw new Error("Must be a positive number");
          }
          break;
        case "ReminderAlerts":
        case "QuickActions":
        case "RecentActivity":
          parsedValue = JSON.parse(formData.value);
          if (!Array.isArray(parsedValue)) {
            throw new Error("Must be an array");
          }
          break;
        default:
          parsedValue = formData.value;
      }

      if (dashboardData) {
        const updatedData = { 
          ...dashboardData, 
          [field]: parsedValue,
          updatedAt: new Date().toISOString()
        };

        // Recalculate PendingStock if TodayArrivals or TodaySales changed
        if (field === "TodayArrivals" || field === "TodaySales") {
          const PendingStock: ProductQuantity = {};
          const arrivals = field === "TodayArrivals" ? parsedValue : dashboardData.TodayArrivals;
          const sales = field === "TodaySales" ? parsedValue : dashboardData.TodaySales;
          
          // Get all unique products
          const allProducts = new Set([...Object.keys(arrivals), ...Object.keys(sales)]);
          allProducts.forEach(product => {
            const arrivalQty = arrivals[product as keyof typeof arrivals] || 0;
            const salesQty = sales[product as keyof typeof sales] || 0;
            PendingStock[product] = arrivalQty - salesQty;
          });
          
          updatedData.PendingStock = PendingStock;
        }

        setDashboardData(updatedData);
        toast({
          title: "Success",
          description: `${field} updated successfully`
        });
      }
    } catch (error) {
      toast({
        title: "Error",
        description: `Invalid format: ${error instanceof Error ? error.message : 'Please check your input'}`,
        variant: "destructive"
      });
      return;
    }

    setIsModalOpen(false);
  };

  const handleDelete = () => {
    setIsDeleteModalOpen(true);
  };

  const handleConfirmDelete = () => {
    if (dashboardData) {
      // Reset all data to empty/default state
      const resetData: DashboardData = {
        ...dashboardData,
        TodayArrivals: {},
        TodaySales: {},
        PendingStock: {},
        PendingBalance: 0,
        PendingKhata: 0,
        ReminderAlerts: [],
        QuickActions: ["Add New Lot", "Create Bill", "Send Invoice"],
        RecentActivity: [],
        updatedAt: new Date().toISOString()
      };
      
      setDashboardData(resetData);
      setIsDeleteModalOpen(false);
      toast({
        title: "Success",
        description: "Dashboard data cleared successfully"
      });
    }
  };

  const handlePrint = () => {
    if (dashboardData) {
      // Create a printable view
      const printContent = `
        <html>
          <head>
            <title>Mandi360pro Dashboard - ${currentFY}</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 20px; }
              h1 { color: #333; border-bottom: 2px solid #90EE90; }
              .section { margin: 20px 0; }
              .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
              .card { border: 1px solid #90EE90; padding: 15px; border-radius: 8px; }
              .card h3 { margin-top: 0; color: #555; }
              table { width: 100%; border-collapse: collapse; }
              th, td { padding: 8px; border: 1px solid #ddd; text-align: left; }
              th { background-color: #f5f5f5; }
            </style>
          </head>
          <body>
            <h1>Mandi360pro Dashboard Summary</h1>
            <p><strong>Financial Year:</strong> ${currentFY}</p>
            <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
            
            <div class="grid">
              <div class="card">
                <h3>Today's Arrivals</h3>
                <table>
                  <tr><th>Product</th><th>Quantity</th></tr>
                  ${Object.entries(dashboardData.TodayArrivals).map(([product, qty]) => 
                    `<tr><td>${product}</td><td>${qty}</td></tr>`
                  ).join('')}
                </table>
              </div>
              
              <div class="card">
                <h3>Today's Sales</h3>
                <table>
                  <tr><th>Product</th><th>Quantity</th></tr>
                  ${Object.entries(dashboardData.TodaySales).map(([product, qty]) => 
                    `<tr><td>${product}</td><td>${qty}</td></tr>`
                  ).join('')}
                </table>
              </div>
              
              <div class="card">
                <h3>Pending Stock</h3>
                <table>
                  <tr><th>Product</th><th>Quantity</th></tr>
                  ${Object.entries(dashboardData.PendingStock).map(([product, qty]) => 
                    `<tr><td>${product}</td><td>${qty}</td></tr>`
                  ).join('')}
                </table>
              </div>
              
              <div class="card">
                <h3>Pending Balance</h3>
                <p><strong>Cash/Balance:</strong> ₹${dashboardData.PendingBalance.toLocaleString()}</p>
                <p><strong>Khata:</strong> ₹${dashboardData.PendingKhata.toLocaleString()}</p>
                <p><strong>Total:</strong> ₹${(dashboardData.PendingBalance + dashboardData.PendingKhata).toLocaleString()}</p>
              </div>
            </div>
            
            <div class="section">
              <h3>Reminder Alerts</h3>
              <ul>
                ${dashboardData.ReminderAlerts.map(alert => 
                  `<li>${alert.Message} - Due: ${alert.Date}</li>`
                ).join('')}
              </ul>
            </div>
            
            <div class="section">
              <h3>Recent Activity</h3>
              <ul>
                ${dashboardData.RecentActivity.map(activity => 
                  `<li>${activity.Activity} - ${activity.Timestamp}</li>`
                ).join('')}
              </ul>
            </div>
          </body>
        </html>
      `;
      
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(printContent);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
        printWindow.close();
      }
      
      toast({
        title: "Success",
        description: "Dashboard summary opened for printing"
      });
    }
  };

  const toggleReminders = () => {
    if (dashboardData && dashboardData.ReminderAlerts.length > 0) {
      const overdueCount = dashboardData.ReminderAlerts.filter(alert => 
        new Date(alert.Date) <= new Date()
      ).length;
      
      toast({
        title: "Reminder Alerts",
        description: `${overdueCount} reminder(s) are overdue, ${dashboardData.ReminderAlerts.length} total alerts`,
        variant: overdueCount > 0 ? "destructive" : "default"
      });
    } else {
      toast({
        title: "No Reminders",
        description: "No reminders are currently set"
      });
    }
  };

  // Helper function to convert ProductQuantity to chart data
  const convertToChartData = (data: ProductQuantity) => {
    return Object.entries(data).map(([product, quantity]) => ({
      product,
      quantity
    }));
  };

  if (!dashboardData) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-lg">Loading Dashboard...</div>
      </div>
    );
  }

  const overdueAlerts = dashboardData.ReminderAlerts.filter(alert => 
    new Date(alert.Date) <= new Date()
  );

  return (
    <div className="p-6 space-y-6">
      {/* Header with Action Buttons */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-display font-bold">Dashboard Module</h1>
          <p className="text-muted-foreground">
            Financial Year {currentFY} Overview • Live Data from Mandi360pro
          </p>
        </div>
        
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleAdd}
            className="gap-2"
            data-testid="button-add-data"
          >
            <Plus className="h-4 w-4" />
            Add (Ctrl+N)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleEdit("TodayArrivals")}
            className="gap-2"
            data-testid="button-edit-data"
          >
            <Edit className="h-4 w-4" />
            Edit (Ctrl+E)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleDelete}
            className="gap-2"
            data-testid="button-delete-data"
          >
            <Trash2 className="h-4 w-4" />
            Delete (Ctrl+D)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handlePrint}
            className="gap-2"
            data-testid="button-print"
          >
            <Printer className="h-4 w-4" />
            Print (Ctrl+P)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={toggleReminders}
            className="gap-2 relative"
            data-testid="button-reminders"
          >
            {overdueAlerts.length > 0 ? (
              <>
                <Bell className="h-4 w-4 text-destructive" />
                <Badge className="absolute -top-1 -right-1 h-5 w-5 rounded-full p-0 text-xs bg-destructive">
                  {overdueAlerts.length}
                </Badge>
              </>
            ) : (
              <BellOff className="h-4 w-4" />
            )}
            Reminders (Ctrl+R)
          </Button>
        </div>
      </div>

      {/* Dashboard Cards Grid - 2x4 Layout with 300px cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-[1400px] mx-auto">
        
        {/* Today's Arrivals Card */}
        <Card
          className="w-[300px] h-[250px] border-2 hover:scale-105 transition-all duration-300 hover-elevate cursor-pointer"
          style={{ borderColor: '#90EE90' }}
          onClick={() => handleEdit("TodayArrivals")}
          data-testid="card-todays-arrivals"
        >
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <BarChart3 className="h-4 w-4" />
              Today's Arrivals
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[180px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={convertToChartData(dashboardData.TodayArrivals)}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="product" fontSize={10} />
                <YAxis fontSize={10} />
                <Tooltip />
                <Bar dataKey="quantity" fill="#90EE90" />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Today's Sales Card */}
        <Card
          className="w-[300px] h-[250px] border-2 hover:scale-105 transition-all duration-300 hover-elevate cursor-pointer"
          style={{ borderColor: '#90EE90' }}
          onClick={() => handleEdit("TodaySales")}
          data-testid="card-todays-sales"
        >
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <TrendingUp className="h-4 w-4" />
              Today's Sales
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[180px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={convertToChartData(dashboardData.TodaySales)}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="product" fontSize={10} />
                <YAxis fontSize={10} />
                <Tooltip />
                <Bar dataKey="quantity" fill="#FF6B6B" />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Pending Stock Card */}
        <Card
          className="w-[300px] h-[250px] border-2 hover:scale-105 transition-all duration-300 hover-elevate"
          style={{ borderColor: '#90EE90' }}
          data-testid="card-pending-stock"
        >
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <Package className="h-4 w-4" />
              Pending Stock (Auto-calculated)
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[180px] overflow-auto">
            <div className="space-y-2">
              {Object.entries(dashboardData.PendingStock).map(([product, quantity]) => (
                <div key={product} className="flex justify-between items-center p-2 bg-secondary/20 rounded-md">
                  <span className="text-sm font-medium">{product}</span>
                  <Badge variant={quantity > 0 ? "default" : "destructive"} className="text-xs">
                    {quantity}
                  </Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Pending Balance Card */}
        <Card
          className="w-[300px] h-[250px] border-2 hover:scale-105 transition-all duration-300 hover-elevate cursor-pointer"
          style={{ borderColor: '#90EE90' }}
          onClick={() => handleEdit("PendingBalance")}
          data-testid="card-pending-balance"
        >
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <DollarSign className="h-4 w-4" />
              Pending Balance
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[180px]">
            <div className="space-y-4">
              <div className="text-center">
                <div className="text-2xl font-bold text-foreground">
                  ₹{(dashboardData.PendingBalance + dashboardData.PendingKhata).toLocaleString()}
                </div>
                <div className="text-xs text-muted-foreground">Total Outstanding</div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between items-center p-2 bg-blue-50 dark:bg-blue-950 rounded-md">
                  <span className="text-sm">Cash/Balance</span>
                  <span className="text-sm font-medium">₹{dashboardData.PendingBalance.toLocaleString()}</span>
                </div>
                <div className="flex justify-between items-center p-2 bg-orange-50 dark:bg-orange-950 rounded-md">
                  <span className="text-sm">Khata</span>
                  <span className="text-sm font-medium">₹{dashboardData.PendingKhata.toLocaleString()}</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Reminder Alerts Card */}
        <Card
          className="w-[300px] h-[250px] border-2 hover:scale-105 transition-all duration-300 hover-elevate cursor-pointer"
          style={{ borderColor: '#90EE90' }}
          onClick={() => handleEdit("ReminderAlerts")}
          data-testid="card-reminder-alerts"
        >
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <Bell className="h-4 w-4" />
              Reminder Alerts
              {overdueAlerts.length > 0 && (
                <Badge variant="destructive" className="text-xs ml-2">
                  {overdueAlerts.length} overdue
                </Badge>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[180px] overflow-auto">
            <div className="space-y-2">
              {dashboardData.ReminderAlerts.map((alert, index) => {
                const isOverdue = new Date(alert.Date) <= new Date();
                return (
                  <div key={index} className={`p-2 rounded-md border-l-4 ${
                    isOverdue ? 'bg-destructive/10 border-destructive' : 'bg-secondary/20 border-primary'
                  }`}>
                    <div className="text-sm font-medium">{alert.Message}</div>
                    <div className="text-xs text-muted-foreground">Due: {alert.Date}</div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>

        {/* Quick Actions Card */}
        <Card
          className="w-[300px] h-[250px] border-2 hover:scale-105 transition-all duration-300 hover-elevate cursor-pointer"
          style={{ borderColor: '#90EE90', backgroundColor: '#90EE90', backgroundImage: 'linear-gradient(rgba(144, 238, 144, 0.1), rgba(144, 238, 144, 0.1))' }}
          onClick={() => handleEdit("QuickActions")}
          data-testid="card-quick-actions"
        >
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <Activity className="h-4 w-4" />
              Quick Actions
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[180px]">
            <div className="grid grid-cols-2 gap-2">
              {dashboardData.QuickActions.map((action, index) => (
                <Button
                  key={index}
                  variant="outline"
                  size="sm"
                  className="text-xs h-8 bg-white/80 hover:bg-white"
                  data-testid={`quick-action-${index}`}
                >
                  {action}
                </Button>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Recent Activity Card */}
        <Card
          className="w-[300px] h-[250px] border-2 hover:scale-105 transition-all duration-300 hover-elevate cursor-pointer"
          style={{ borderColor: '#90EE90' }}
          onClick={() => handleEdit("RecentActivity")}
          data-testid="card-recent-activity"
        >
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
              <Activity className="h-4 w-4" />
              Recent Activity
            </CardTitle>
          </CardHeader>
          <CardContent className="h-[180px] overflow-auto">
            <div className="space-y-2">
              {dashboardData.RecentActivity.map((activity, index) => (
                <div 
                  key={index} 
                  className="p-2 bg-secondary/20 rounded-md animate-in fade-in slide-in-from-bottom-2"
                  style={{ animationDelay: `${index * 100}ms` }}
                >
                  <div className="text-sm font-medium">{activity.Activity}</div>
                  <div className="text-xs text-muted-foreground">{activity.Timestamp}</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Add New Data Card */}
        <Card
          className="w-[300px] h-[250px] border-2 border-dashed border-muted-foreground/25 hover:border-primary cursor-pointer transition-all duration-300 hover:scale-105 flex items-center justify-center hover-elevate"
          onClick={handleAdd}
          data-testid="card-add-new"
        >
          <div className="text-center">
            <Plus className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">Add New Data</p>
            <p className="text-xs text-muted-foreground">Ctrl+N</p>
          </div>
        </Card>
      </div>

      {/* Add/Edit Modal */}
      <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle>
              {editingField ? `Edit ${editingField}` : 'Add Dashboard Data'}
            </DialogTitle>
            <DialogDescription>
              Update dashboard data for Financial Year {currentFY}. Enter JSON format for complex fields.
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="field">Data Field *</Label>
              <Select 
                value={formData.field} 
                onValueChange={(value) => setFormData(prev => ({ ...prev, field: value }))}
              >
                <SelectTrigger data-testid="select-data-field">
                  <SelectValue placeholder="Select field to edit" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="TodayArrivals">Today's Arrivals</SelectItem>
                  <SelectItem value="TodaySales">Today's Sales</SelectItem>
                  <SelectItem value="PendingBalance">Pending Balance</SelectItem>
                  <SelectItem value="PendingKhata">Pending Khata</SelectItem>
                  <SelectItem value="ReminderAlerts">Reminder Alerts</SelectItem>
                  <SelectItem value="QuickActions">Quick Actions</SelectItem>
                  <SelectItem value="RecentActivity">Recent Activity</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="value">Data Value *</Label>
              <Textarea
                id="value"
                value={formData.value}
                onChange={(e) => setFormData(prev => ({ ...prev, value: e.target.value }))}
                placeholder={getPlaceholderForField(formData.field)}
                rows={6}
                className="font-mono text-sm"
                data-testid="textarea-data-value"
              />
              <div className="text-xs text-muted-foreground">
                {getHelpTextForField(formData.field)}
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="fy">Financial Year</Label>
              <Select 
                value={formData.fy} 
                onValueChange={(value) => setFormData(prev => ({ ...prev, fy: value }))}
              >
                <SelectTrigger data-testid="select-data-fy">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="2024-25">2024-25</SelectItem>
                  <SelectItem value="2025-26">2025-26</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <DialogFooter>
            <Button 
              variant="outline" 
              onClick={() => setIsModalOpen(false)}
              data-testid="button-cancel-modal"
            >
              Cancel
            </Button>
            <Button 
              onClick={handleSave}
              className="gap-2"
              data-testid="button-save-modal"
            >
              <Save className="h-4 w-4" />
              Save (Ctrl+S)
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={isDeleteModalOpen} onOpenChange={setIsDeleteModalOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Clear Dashboard Data</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to clear all dashboard data for FY {currentFY}? 
              This will reset all arrivals, sales, balances, alerts, and activity. 
              This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel data-testid="button-cancel-delete">
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirmDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              data-testid="button-confirm-delete"
            >
              Clear All Data
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );

  // Helper functions for modal
  function getPlaceholderForField(field: string): string {
    switch (field) {
      case "TodayArrivals":
      case "TodaySales":
        return '{"Onion": 250, "Potato": 500, "Garlic": 70}';
      case "PendingBalance":
      case "PendingKhata":
        return '25000';
      case "ReminderAlerts":
        return '[{"Message": "Suraj Varma ₹2000 overdue", "Date": "2025-09-21"}]';
      case "QuickActions":
        return '["Add New Lot", "Create Bill", "Send Invoice"]';
      case "RecentActivity":
        return '[{"Activity": "Sold 150 Onion", "Timestamp": "2025-09-21 07:00"}]';
      default:
        return "";
    }
  }

  function getHelpTextForField(field: string): string {
    switch (field) {
      case "TodayArrivals":
      case "TodaySales":
        return "JSON object with product names as keys and quantities as numbers";
      case "PendingBalance":
      case "PendingKhata":
        return "Number representing amount in rupees";
      case "ReminderAlerts":
        return "Array of objects with Message (string) and Date (YYYY-MM-DD)";
      case "QuickActions":
        return "Array of action button labels";
      case "RecentActivity":
        return "Array of objects with Activity (string) and Timestamp (YYYY-MM-DD HH:MM)";
      default:
        return "";
    }
  }
}