import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { toast } from "@/hooks/use-toast";
import { 
  Plus, 
  Edit, 
  Trash2, 
  Save, 
  Printer, 
  Bell, 
  BellOff,
  AlertTriangle,
  TrendingUp,
  Package,
  Users,
  DollarSign
} from "lucide-react";

interface DashboardCard {
  id: string;
  title: string;
  value: string;
  fy: string;
  reminderDate?: string;
  createdAt: string;
  updatedAt: string;
}

interface DashboardModuleProps {
  currentFY: string;
  onFYChange: (fy: string) => void;
}

// Mock data for testing - in real app this would come from integrated modules
const getMockCardValue = (title: string, fy: string): string => {
  const mockData: Record<string, Record<string, string>> = {
    "Today's Lots": {
      "2024-25": "Onion-120, Potato-450, Wheat-300",
      "2025-26": "Onion-150, Potato-500, Wheat-280"
    },
    "Pending Payments": {
      "2024-25": "₹85,000 (12 bills)",
      "2025-26": "₹1,25,000 (18 bills)"
    },
    "Account Balance": {
      "2024-25": "₹5,50,000 Credit",
      "2025-26": "₹7,25,000 Credit"
    },
    "Active Farmers": {
      "2024-25": "45 Registered",
      "2025-26": "58 Registered"
    }
  };
  
  return mockData[title]?.[fy] || "No data";
};

const generatePDF = (cards: DashboardCard[], fy: string) => {
  const content = `
MANDI360PRO - DASHBOARD SUMMARY
Financial Year: ${fy}
Generated: ${new Date().toLocaleString()}
================================

${cards.map(card => `
${card.title.toUpperCase()}
Value: ${card.value}
${card.reminderDate ? `Reminder: ${card.reminderDate}` : ''}
---`).join('\n')}

Total Cards: ${cards.length}
Report generated by Mandi360pro
  `;
  
  // Create and download as text file (in real app, would use proper PDF library)
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `dashboard-summary-${fy}-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export default function DashboardModule({ currentFY, onFYChange }: DashboardModuleProps) {
  const [cards, setCards] = useState<DashboardCard[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingCard, setEditingCard] = useState<DashboardCard | null>(null);
  const [deleteCard, setDeleteCard] = useState<DashboardCard | null>(null);
  const [reminderAlerts, setReminderAlerts] = useState<DashboardCard[]>([]);
  
  const [formData, setFormData] = useState({
    title: "",
    value: "",
    fy: currentFY,
    reminderDate: ""
  });

  // Load cards from localStorage on mount
  useEffect(() => {
    const savedCards = localStorage.getItem('mandi360pro-dashboard-cards');
    if (savedCards) {
      try {
        const parsedCards = JSON.parse(savedCards);
        setCards(parsedCards);
      } catch (error) {
        console.error('Error loading cards from localStorage:', error);
      }
    } else {
      // Initialize with default cards
      const defaultCards: DashboardCard[] = [
        {
          id: '1',
          title: "Today's Lots",
          value: getMockCardValue("Today's Lots", currentFY),
          fy: currentFY,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        },
        {
          id: '2',
          title: "Pending Payments",
          value: getMockCardValue("Pending Payments", currentFY),
          fy: currentFY,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        },
        {
          id: '3',
          title: "Account Balance",
          value: getMockCardValue("Account Balance", currentFY),
          fy: currentFY,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        }
      ];
      setCards(defaultCards);
      localStorage.setItem('mandi360pro-dashboard-cards', JSON.stringify(defaultCards));
    }
  }, [currentFY]);

  // Save cards to localStorage whenever cards change
  useEffect(() => {
    localStorage.setItem('mandi360pro-dashboard-cards', JSON.stringify(cards));
  }, [cards]);

  // Check for reminder alerts
  useEffect(() => {
    const today = new Date().toISOString().split('T')[0];
    const alertCards = cards.filter(card => 
      card.reminderDate && card.reminderDate <= today
    );
    setReminderAlerts(alertCards);
  }, [cards]);

  // Update card values when FY changes
  useEffect(() => {
    setCards(prevCards => 
      prevCards.map(card => ({
        ...card,
        value: getMockCardValue(card.title, currentFY)
      }))
    );
  }, [currentFY]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.ctrlKey) {
        switch (e.key.toLowerCase()) {
          case 'n':
            e.preventDefault();
            handleAdd();
            break;
          case 'e':
            e.preventDefault();
            if (cards.length > 0) {
              handleEdit(cards[0]); // Edit first card if none selected
            }
            break;
          case 'd':
            e.preventDefault();
            if (cards.length > 0) {
              setDeleteCard(cards[0]); // Delete first card if none selected
            }
            break;
          case 's':
            e.preventDefault();
            if (isModalOpen) {
              handleSave();
            }
            break;
          case 'p':
            e.preventDefault();
            handlePrint();
            break;
          case 'r':
            e.preventDefault();
            toggleReminders();
            break;
        }
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [isModalOpen, cards]);

  const handleAdd = () => {
    setEditingCard(null);
    setFormData({
      title: "",
      value: "",
      fy: currentFY,
      reminderDate: ""
    });
    setIsModalOpen(true);
  };

  const handleEdit = (card: DashboardCard) => {
    setEditingCard(card);
    setFormData({
      title: card.title,
      value: card.value,
      fy: card.fy,
      reminderDate: card.reminderDate || ""
    });
    setIsModalOpen(true);
  };

  const handleSave = () => {
    // Validation
    if (!formData.title.trim()) {
      toast({
        title: "Error",
        description: "Card title is required",
        variant: "destructive"
      });
      return;
    }

    if (!formData.value.trim()) {
      toast({
        title: "Error", 
        description: "Card value is required and must be greater than 0",
        variant: "destructive"
      });
      return;
    }

    if (formData.reminderDate) {
      const reminderDate = new Date(formData.reminderDate);
      if (isNaN(reminderDate.getTime())) {
        toast({
          title: "Error",
          description: "Invalid reminder date",
          variant: "destructive"
        });
        return;
      }
    }

    const now = new Date().toISOString();
    
    if (editingCard) {
      // Update existing card
      setCards(prevCards =>
        prevCards.map(card =>
          card.id === editingCard.id
            ? {
                ...card,
                title: formData.title,
                value: formData.value,
                fy: formData.fy,
                reminderDate: formData.reminderDate || undefined,
                updatedAt: now
              }
            : card
        )
      );
      toast({
        title: "Success",
        description: "Card updated successfully"
      });
    } else {
      // Add new card
      const newCard: DashboardCard = {
        id: Date.now().toString(),
        title: formData.title,
        value: formData.value,
        fy: formData.fy,
        reminderDate: formData.reminderDate || undefined,
        createdAt: now,
        updatedAt: now
      };
      setCards(prevCards => [...prevCards, newCard]);
      toast({
        title: "Success",
        description: "Card added successfully"
      });
    }

    setIsModalOpen(false);
  };

  const handleDelete = (card: DashboardCard) => {
    setCards(prevCards => prevCards.filter(c => c.id !== card.id));
    setDeleteCard(null);
    toast({
      title: "Success",
      description: "Card deleted successfully"
    });
  };

  const handlePrint = () => {
    generatePDF(cards.filter(card => card.fy === currentFY), currentFY);
    toast({
      title: "Success",
      description: "Dashboard summary downloaded"
    });
  };

  const toggleReminders = () => {
    if (reminderAlerts.length > 0) {
      toast({
        title: "Reminder Alerts",
        description: `${reminderAlerts.length} reminder(s) are due!`,
        variant: "destructive"
      });
    } else {
      toast({
        title: "No Reminders",
        description: "No reminders are currently due"
      });
    }
  };

  const filteredCards = cards.filter(card => card.fy === currentFY);

  return (
    <div className="p-6 space-y-6">
      {/* Header with Action Buttons */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-display font-bold">Dashboard Module</h1>
          <p className="text-muted-foreground">
            Financial Year {currentFY} Overview • {filteredCards.length} cards
          </p>
        </div>
        
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleAdd}
            className="gap-2"
            data-testid="button-add-card"
          >
            <Plus className="h-4 w-4" />
            Add (Ctrl+N)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => filteredCards.length > 0 && handleEdit(filteredCards[0])}
            className="gap-2"
            disabled={filteredCards.length === 0}
            data-testid="button-edit-card"
          >
            <Edit className="h-4 w-4" />
            Edit (Ctrl+E)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => filteredCards.length > 0 && setDeleteCard(filteredCards[0])}
            className="gap-2"
            disabled={filteredCards.length === 0}
            data-testid="button-delete-card"
          >
            <Trash2 className="h-4 w-4" />
            Delete (Ctrl+D)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handlePrint}
            className="gap-2"
            data-testid="button-print"
          >
            <Printer className="h-4 w-4" />
            Print (Ctrl+P)
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={toggleReminders}
            className="gap-2 relative"
            data-testid="button-reminders"
          >
            {reminderAlerts.length > 0 ? (
              <>
                <Bell className="h-4 w-4 text-destructive" />
                <Badge className="absolute -top-1 -right-1 h-5 w-5 rounded-full p-0 text-xs">
                  {reminderAlerts.length}
                </Badge>
              </>
            ) : (
              <BellOff className="h-4 w-4" />
            )}
            Reminders (Ctrl+R)
          </Button>
        </div>
      </div>

      {/* Reminder Alerts */}
      {reminderAlerts.length > 0 && (
        <Card className="border-destructive">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center gap-2 text-destructive">
              <AlertTriangle className="h-5 w-5" />
              Reminder Alerts
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {reminderAlerts.map(card => (
                <div key={card.id} className="flex items-center justify-between p-2 bg-destructive/10 rounded-md">
                  <span className="text-sm font-medium">{card.title}</span>
                  <Badge variant="destructive" className="text-xs">
                    Due: {card.reminderDate}
                  </Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Dashboard Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredCards.map((card, index) => (
          <Card
            key={card.id}
            className="w-full max-w-[300px] border-2 border-primary/20 hover:border-primary hover:scale-105 transition-all duration-300 hover-elevate cursor-pointer animate-in fade-in slide-in-from-bottom-4"
            style={{ animationDelay: `${index * 100}ms` }}
            onClick={() => handleEdit(card)}
            data-testid={`card-${card.id}`}
          >
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  {card.title}
                </CardTitle>
                <div className="flex items-center gap-1">
                  {card.reminderDate && (
                    <Bell className="h-3 w-3 text-primary" />
                  )}
                  <div className="flex gap-1">
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-6 w-6"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleEdit(card);
                      }}
                      data-testid={`button-edit-${card.id}`}
                    >
                      <Edit className="h-3 w-3" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-6 w-6"
                      onClick={(e) => {
                        e.stopPropagation();
                        setDeleteCard(card);
                      }}
                      data-testid={`button-delete-${card.id}`}
                    >
                      <Trash2 className="h-3 w-3" />
                    </Button>
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                <div className="text-lg font-bold text-foreground break-words">
                  {card.value}
                </div>
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                  <span>FY: {card.fy}</span>
                  {card.reminderDate && (
                    <span className="text-primary">📅 {card.reminderDate}</span>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
        
        {/* Add Card Button */}
        <Card
          className="w-full max-w-[300px] border-2 border-dashed border-muted-foreground/25 hover:border-primary cursor-pointer transition-all duration-300 hover:scale-105 flex items-center justify-center min-h-[140px] hover-elevate"
          onClick={handleAdd}
          data-testid="card-add-new"
        >
          <div className="text-center">
            <Plus className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">Add New Card</p>
            <p className="text-xs text-muted-foreground">Ctrl+N</p>
          </div>
        </Card>
      </div>

      {/* Add/Edit Modal */}
      <Dialog open={isModalOpen} onOpenChange={setIsModalOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>
              {editingCard ? 'Edit Dashboard Card' : 'Add Dashboard Card'}
            </DialogTitle>
            <DialogDescription>
              Create or modify dashboard cards to track important metrics for FY {currentFY}.
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="title">Card Title *</Label>
              <Input
                id="title"
                value={formData.title}
                onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
                placeholder="e.g., Today's Lots with product and quantity"
                data-testid="input-card-title"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="value">Card Value *</Label>
              <Textarea
                id="value"
                value={formData.value}
                onChange={(e) => setFormData(prev => ({ ...prev, value: e.target.value }))}
                placeholder="e.g., Onion-150, Potato-500, Wheat-280"
                rows={2}
                data-testid="textarea-card-value"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="fy">Financial Year</Label>
              <Select 
                value={formData.fy} 
                onValueChange={(value) => setFormData(prev => ({ ...prev, fy: value }))}
              >
                <SelectTrigger data-testid="select-card-fy">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="2024-25">2024-25</SelectItem>
                  <SelectItem value="2025-26">2025-26</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="reminderDate">Reminder Date (Optional)</Label>
              <Input
                id="reminderDate"
                type="date"
                value={formData.reminderDate}
                onChange={(e) => setFormData(prev => ({ ...prev, reminderDate: e.target.value }))}
                data-testid="input-reminder-date"
              />
              <p className="text-xs text-muted-foreground">
                Set a reminder date to get alerts when the date is reached
              </p>
            </div>
          </div>

          <DialogFooter>
            <Button 
              variant="outline" 
              onClick={() => setIsModalOpen(false)}
              data-testid="button-cancel-modal"
            >
              Cancel
            </Button>
            <Button 
              onClick={handleSave}
              className="gap-2"
              data-testid="button-save-modal"
            >
              <Save className="h-4 w-4" />
              Save (Ctrl+S)
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={!!deleteCard} onOpenChange={() => setDeleteCard(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Dashboard Card</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete the card "{deleteCard?.title}"? 
              This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel data-testid="button-cancel-delete">
              Cancel
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => deleteCard && handleDelete(deleteCard)}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              data-testid="button-confirm-delete"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}